<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AfdelingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfdelingRepository extends EntityRepository
{
	public function findIngredientenByAfdeling($boodschappenlijst)
	{    	
    	return $this->getEntityManager()->createQueryBuilder()
    		->select('a','ibl')
    		->from('AppBundle:Afdeling','a')
    		->join('a.ingrbl', 'ibl')
    		->where('ibl.boodschappenlijst = :boodschappenlijst')
			->setParameter('boodschappenlijst', $boodschappenlijst)
    		->orderBy('a.name')
    		->getQuery()
    		->getResult();
    }
}
