<?php

namespace AppBundle\Repository;

/**
 * DagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DagRepository extends \Doctrine\ORM\EntityRepository
{
}
