<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KeukenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeukenRepository extends EntityRepository
{
	public function findAllByUser(\AppBundle\Entity\User $user) {
		return $this->createQueryBuilder('k')
			->leftJoin('k.recepten', 'r')
			->addSelect('r')
			->where('r.user = :user')
			->setParameter('user', $user)
			->getQuery()
			->getResult();
	}

}
