<?php

namespace AppBundle\Repository;

/**
 * MealplanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealplanRepository extends \Doctrine\ORM\EntityRepository
{
}
