<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
	public function findIngredientenByMenu($id){
		return $this->getEntityManager()->createQueryBuilder()
// 			->select('a', 'i')
// 			->from('AppBundle:Afdeling','a')
// 			->join('a.ingredienten', 'i')
// 			->join('i.recept', 'r')
// 			->join('r.menus', 'm')
// 			->where('m.id = :menuid')
// 			->setParameter('menuid', $id)			
// 			->orderBy('a.name')
// 			->getQuery()
// 			->getResult();
			->select('a', 'i')
			->from('AppBundle:Afdeling','a')
			->join('a.ingredienten', 'i')
			->join('i.recept', 'r')
			->join('r.dagen', 'd')
			->where('d.menu = :menuid')
			->setParameter('menuid', $id)			
			->orderBy('a.name')
			->getQuery()
			->getResult();
	}

}
