<?php

namespace AppBundle\Repository;

/**
 * YieldTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YieldTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
